CREATE TABLE  GI_BUSINESS_AREAS
   (	BA_ID NUMBER ,
	DIR_ID NUMBER,
	BA_NAME VARCHAR2(100),
	START_DATE DATE,
	END_DATE DATE,
	CREATED_BY NUMBER,
	CREATION_DATE DATE,
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY NUMBER,
	 CONSTRAINT BA_ID_PK PRIMARY KEY (BA_ID)
  USING INDEX  ENABLE
   );

   CREATE TABLE  GI_COMMENTS
      (	COM_ID NUMBER,
   	GREAT_IDEAS_COMMENTS VARCHAR2(4000),
   	USER_ID NUMBER,
   	STATUS_AT_COMMENT_TIME VARCHAR2(50),
   	COMMENT_DATE DATE,
   	CREATION_DATE DATE,
   	CREATED_BY NUMBER,
   	LAST_UPDATED_BY NUMBER,
   	LAST_UPDATE_DATE DATE,
   	CATEGORY VARCHAR2(100),
   	GI_REF VARCHAR2(50),
   	 CONSTRAINT GI_COMMENTS_PK PRIMARY KEY (COM_ID)
     USING INDEX  ENABLE
      );

      CREATE TABLE  GI_DIRECTORATE
         (	DIR_ID NUMBER,
      	DIR_NAME VARCHAR2(100),
      	START_DATE DATE,
      	END_DATE DATE,
      	CREATED_BY NUMBER,
      	CREATION_DATE DATE,
      	LAST_UPDATE_DATE DATE,
      	LAST_UPDATED_BY NUMBER,
      	 CONSTRAINT DIR_ID_PK PRIMARY KEY (DIR_ID)
        USING INDEX  ENABLE
         );

         CREATE TABLE  GI_IDEAS
            (	GI_ID NUMBER,
         	GI_REF VARCHAR2(50),
         	DATE_LOGGED DATE NOT NULL ENABLE,
         	INITIATOR_ID NUMBER NOT NULL ENABLE,
         	AREA_AFFECTED VARCHAR2(50),
         	TITLE_OF_IDEA VARCHAR2(100),
         	IDEA VARCHAR2(4000),
         	BENEFITS VARCHAR2(4000),
         	BENEFITS_TAGS VARCHAR2(500),
         	INITIATOR_INVOLVEMENT VARCHAR2(50),
         	CURRENT_STATUS VARCHAR2(50),
         	CREATION_DATE DATE,
         	CREATED_BY NUMBER,
         	LAST_UPDATED_BY NUMBER,
         	LAST_UPDATE_DATE DATE,
         	REVIEW_DATE DATE,
         	ALLOCATED_TO VARCHAR2(100),
         	PARTICIPATION_LEVEL VARCHAR2(100),
         	VOTE_COUNT NUMBER DEFAULT '0',
         	INI_COMPLAINT_COUNT NUMBER DEFAULT NULL,
         	INI_ERROR_COUNT NUMBER DEFAULT NULL,
         	INI_REJECTS NUMBER DEFAULT NULL,
         	INI_RESOURCE_HOURS NUMBER DEFAULT NULL,
         	INI_RISK NUMBER DEFAULT NULL,
         	INI_STAFF_SURVEY_RESULTS VARCHAR2(1000) DEFAULT NULL,
         	INI_COST NUMBER DEFAULT NULL,
         	POST_COMPLAINT_COUNT NUMBER DEFAULT NULL,
         	POST_ERROR_COUNT NUMBER DEFAULT NULL,
         	POST_REJECTS NUMBER DEFAULT NULL,
         	POST_RESOURCE_HOURS NUMBER DEFAULT NULL,
         	POST_RISK NUMBER DEFAULT NULL,
         	POST_STAFF_SURVEY_RESULTS VARCHAR2(1000) DEFAULT NULL,
         	POST_COST NUMBER DEFAULT NULL,
         	INI_IMPACT NUMBER DEFAULT NULL,
         	POST_IMPACT NUMBER DEFAULT NULL,
         	SUBMITTED_DATE DATE,
         	AREA_AFFECTED_DETAIL VARCHAR2(1000),
         	 CONSTRAINT GI_IDEAS_PK PRIMARY KEY (GI_ID)
           USING INDEX  ENABLE
            );

  CREATE TABLE  GI_IT_SYSTEMS
   (	SYS_NAME VARCHAR2(50) NOT NULL ENABLE,
	SYS_ID NUMBER,
	START_DATE DATE,
	END_DATE DATE,
	CREATION_DATE DATE,
	CREATED_BY NUMBER,
	LAST_UPDATED_BY NUMBER,
	LAST_UPDATE_DATE DATE,
	 CONSTRAINT GI_IT_SYSTEMS_PK PRIMARY KEY (SYS_ID)
  USING INDEX  ENABLE
   );

   CREATE TABLE  GI_LOOKUP_TYPES
   (	LOOKUP_TYPE VARCHAR2(150) NOT NULL ENABLE,
	CREATION_DATE DATE,
	CREATED_BY NUMBER,
	LAST_UPDATED_BY NUMBER,
	LAST_UPDATE_DATE DATE,
	 CONSTRAINT GI_LOOKUP_TYPES_PK PRIMARY KEY (LOOKUP_TYPE)
  USING INDEX  ENABLE
   );

   CREATE TABLE  GI_LOOKUP_VALUES
      (	VALUE_ID NUMBER,
   	LOOKUP_TYPE VARCHAR2(150) NOT NULL ENABLE,
   	LOOKUP_VALUE VARCHAR2(150),
   	DESCRIPTION VARCHAR2(450),
   	START_DATE DATE,
   	END_DATE DATE,
   	CREATION_DATE DATE,
   	CREATED_BY NUMBER,
   	LAST_UPDATED_BY NUMBER,
   	LAST_UPDATE_DATE DATE,
   	 CONSTRAINT GI_LOOKUP_VALUES_PK PRIMARY KEY (VALUE_ID)
     USING INDEX  ENABLE
      );

      CREATE TABLE  GI_OFFICE
         (	OFFICE_NAME VARCHAR2(100) NOT NULL ENABLE,
      	OFFICE_ID NUMBER,
      	START_DATE DATE,
      	END_DATE DATE,
      	CREATION_DATE DATE,
      	CREATED_BY NUMBER,
      	LAST_UPDATED_BY NUMBER,
      	LAST_UPDATE_DATE DATE,
      	OFFICE_DESCRIPTION VARCHAR2(50)
         );

         CREATE TABLE  GI_ROLES
   (	ROLE_ID NUMBER,
	ROLE_NAME VARCHAR2(20),
	START_DATE DATE,
	END_DATE DATE,
	CREATION_DATE DATE,
	CREATED_BY NUMBER,
	LAST_UPDATED_BY NUMBER,
	LAST_UPDATE_DATE DATE,
	 CONSTRAINT GI_ROLES_PK PRIMARY KEY (ROLE_ID)
  USING INDEX  ENABLE
   );

CREATE TABLE  GI_STATUS_HISTORY
   (	STAT_HIS_ID NUMBER,
	GI_REF VARCHAR2(50),
	STATUS_CHANGED_TO VARCHAR2(50),
	STATUS_CHANGED_FROM VARCHAR2(50),
	DATE_CHANGED DATE,
	CHANGED_BY NUMBER,
	CREATION_DATE DATE,
	CREATED_BY NUMBER,
	LAST_UPDATED_BY NUMBER,
	LAST_UPDATE_DATE DATE,
	 CONSTRAINT GI_STATUS_HISTORY_PK PRIMARY KEY (STAT_HIS_ID)
  USING INDEX  ENABLE
   );

   CREATE TABLE  GI_TEAMS
   (	TEAM_ID NUMBER,
	BA_ID NUMBER,
	TEAM_NAME VARCHAR2(100),
	START_DATE DATE,
	END_DATE DATE,
	CREATED_BY NUMBER,
	CREATION_DATE DATE,
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY NUMBER
  );

  CREATE TABLE  GI_USERS
   (	USER_ID NUMBER,
	USER_NAME VARCHAR2(100),
	FIRST_NAME VARCHAR2(100),
	LAST_NAME VARCHAR2(100),
	USER_PWD VARCHAR2(100),
	PASSWORD_FLAG NUMBER(10,0),
	EMAIL_ADDRESS VARCHAR2(100),
	USER_CONTACT_NUM VARCHAR2(100),
	ROLE_ID NUMBER NOT NULL ENABLE,
	USER_DIRECTORATE NUMBER,
	USER_BUSINESS_AREA NUMBER,
	USER_BUSINESS_AREA_OTHER VARCHAR2(100),
	USER_TEAM NUMBER,
	USER_TEAM_OTHER VARCHAR2(100),
	OFFICE NUMBER,
	CREATION_DATE DATE,
	CREATED_BY NUMBER,
	LAST_UPDATED_BY NUMBER,
	LAST_UPDATE_DATE DATE,
	USERNAME_CHANGE NUMBER,
	START_DATE DATE,
	END_DATE DATE,
	 CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)
  USING INDEX  ENABLE
   );

   CREATE TABLE  GI_VOTING
   (	VOTE_ID NUMBER,
	GI_REF VARCHAR2(50),
	USER_ID NUMBER,
	CREATION_DATE DATE,
	CREATED_BY NUMBER,
	LAST_UPDATED_BY NUMBER,
	LAST_UPDATE_DATE DATE,
	 CONSTRAINT GI_VOTING_PK PRIMARY KEY (VOTE_ID)
  USING INDEX  ENABLE
   );
