---- Insert dev team and CI team users with role id = 2

--- Dev team

BEGIN

INSERT INTO GI_USERS 		
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE,	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE, END_DATE)	
VALUES		
	('ADMIN', 'ADMIN', 'ADMIN', gi_getMD5('ADMIN'),	
	0, NULL, NULL, 2, NULL, NULL,	
	NULL, NULL, NULL, NULL,	
	SYSDATE, NULL, NULL, SYSDATE, SYSDATE, SYSDATE);	
		
INSERT INTO GI_USERS
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE,	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES
	(upper('Charles.Boardman@legalaid.gsi.gov.uk'), 'Charles', 'Boardman', gi_getMD5(UPPER('PASSWORD123')||UPPER('Charles.Boardman@legalaid.gsi.gov.uk')),
	0,'Charles.Boardman@legalaid.gsi.gov.uk','0000',2,3,10,NULL,38,NULL,'12',
	SYSDATE,1,1, SYSDATE, SYSDATE);


INSERT INTO GI_USERS
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE,	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES
	(upper('Pareis.Pindoria@legalaid.gsi.gov.uk'), 'Pareis', 'Pindoria', gi_getMD5(UPPER('PASSWORD123')||UPPER('Pareis.Pindoria@legalaid.gsi.gov.uk')),
	0,'Pareis.Pindoria@legalaid.gsi.gov.uk','0000',2,3,10,NULL,38,NULL,'12',
	SYSDATE,1,1, SYSDATE, SYSDATE);


INSERT INTO GI_USERS
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE,	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES
	(upper('Alexander.Morris1@legalaid.gsi.gov.uk'), 'Alexander', 'Morris', gi_getMD5(UPPER('PASSWORD123')||UPPER('Alexander.Morris1@legalaid.gsi.gov.uk')),
	0,'Alexander.Morris1@legalaid.gsi.gov.uk','0000',2,3,10,NULL,38,NULL,'12',
	SYSDATE,1,1, SYSDATE, SYSDATE);


INSERT INTO GI_USERS
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE,	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES
	(upper('Deepika.Patel@legalaid.gsi.gov.uk'), 'Deepika', 'Patel', gi_getMD5(UPPER('PASSWORD123')||UPPER('Deepika.Patel@legalaid.gsi.gov.uk')),
	0,'Deepika.Patel@legalaid.gsi.gov.uk','0000',2,3,10,NULL,38,NULL,'12',
	SYSDATE,1,1, SYSDATE, SYSDATE);


INSERT INTO GI_USERS
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE,	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES
	(upper('abdirizak.obsiye@justice.gsi.gov.uk'), 'Abdirizak', 'Obsiye', gi_getMD5(UPPER('PASSWORD123')||UPPER('abdirizak.obsiye@justice.gsi.gov.uk')),
	0,'abdirizak.obsiye@justice.gsi.gov.uk','0000',2,3,10,NULL,38,NULL,'12',
	SYSDATE,1,1, SYSDATE, SYSDATE);

--- CI team
--- Ros - Manchester
--- Vicky - South Tyneside
--- Lee - Nottingham

INSERT INTO GI_USERS		
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE, 	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES		
	(upper('Rosalind.Fawcett@legalaid.gsi.gov.uk'), 'Rosalind', 'Fawcett', gi_getMD5(UPPER('PASSWORD123')||UPPER('Rosalind.Fawcett@legalaid.gsi.gov.uk')),	
	0, 'Rosalind.Fawcett@legalaid.gsi.gov.uk', '07834677348', 2, 3, 27,	
	NULL, 55, NULL, 10,	
	SYSDATE, 1, 1, SYSDATE, SYSDATE);

INSERT INTO GI_USERS		
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE, 	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES		
	(upper('Victoria.Chapman@legalaid.gsi.gov.uk'), 'Victoria', 'Chapman', gi_getMD5(UPPER('PASSWORD123')||UPPER('Victoria.Chapman@legalaid.gsi.gov.uk')),	
	0, 'Victoria.Chapman@legalaid.gsi.gov.uk', '07972320902', 2, 3, 27,	
	NULL, 55, NULL, 15,	
	SYSDATE, 1, 1, SYSDATE, SYSDATE);	
		
INSERT INTO GI_USERS		
	(USER_NAME, FIRST_NAME, LAST_NAME, USER_PWD,	
	PASSWORD_FLAG, EMAIL_ADDRESS, USER_CONTACT_NUM, ROLE_ID, USER_DIRECTORATE, USER_BUSINESS_AREA,	
	USER_BUSINESS_AREA_OTHER, USER_TEAM, USER_TEAM_OTHER, OFFICE, 	
	CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE, START_DATE)	
VALUES		
	(upper('Lee.Foulds@legalaid.gsi.gov.uk'), 'Lee', 'Foulds', gi_getMD5(UPPER('PASSWORD123')||UPPER('Lee.Foulds@legalaid.gsi.gov.uk')),	
	0, 'Lee.Foulds@legalaid.gsi.gov.uk', '07341889405', 2, 3, 27,	
	NULL, 55, NULL, 11,	
	SYSDATE, 1, 1, SYSDATE, SYSDATE);	



COMMIT;
END;	
		
