--- GI_BUSINESS_AREA

begin
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Exceptional and Complex Cases', 1, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Crime',1, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Civil',1, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Delivery / CM Other',1, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Central Commissioning',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Public Defender Service',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Service Development',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Contract Management',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CLA',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Digital',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Assurance',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Finance',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Planning and Performance',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CEO Office',4, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Communications',4, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Operational Change and Improvement',4, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Engagement and Inclusion',4, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Corporate Centre Correspondence',4, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_BUSINESS_AREAS (BA_NAME, DIR_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Central Legal',5, SYSDATE, 1, SYSDATE, SYSDATE, 1);

INSERT INTO GI_BUSINESS_AREAS (BA_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES ('Other', SYSDATE, 1, SYSDATE, SYSDATE, 1);

commit;
end;
