--- GI_TEAMS

Begin
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('High Cost Civil',1, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('ECF',1, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('NIAT',1, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Crime Billing',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('AGFS',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('LGFS',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CAT',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('NCT',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('NCCT',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CCMT',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CCU',2, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Means',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Finance',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Legal',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CST',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('RMC/CPH',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Facilities',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Business Support',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('VHCC',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('FAS/Escaped Cases',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('BIT',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Mental Health/Escaped Cases',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Operations/Digi Ops',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('UPOA',3, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Delivery',4, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Central Commissioning',5, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Advocacy',6, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Solicitors',6, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Operations',6, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Service Development',7, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('West',8, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('East',8, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('London, South East and Bar',8, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CLA',9, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Business Analysis and User Relations',10, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Digital Change',10, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Live Service Support',10, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Digital Delivery',10, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('CCMS Service Delivery',10, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Quality Assurance',11, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Operational Assurance',11, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Corporate Assurance',11, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Financial Management and Business Partnering',12, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Recovery Services',12, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Financial Accounts',12, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Statistics and Analysis',12, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Management Information',13, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Corporate Reporting',13, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Central Change Team',13, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Board Secretariat',14, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Information Governance',14, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Internal Communications',15, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Stakeholder Communications',15, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Operational Change and Improvement',16, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Engagement and Inclusion',17, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Corporate Centre Correspondence',18, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Funding',19, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Litigation',19, SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_TEAMS (TEAM_NAME, BA_ID, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Legal Support',19, SYSDATE, 1, SYSDATE, SYSDATE, 1);

INSERT INTO GI_TEAMS (TEAM_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES ('Other', SYSDATE, 1, SYSDATE, SYSDATE, 1);

COMMIT;
end;

