--- GI_IT_SYSTEMS

Begin	
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME, START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('CCLF', sysdate, sysdate, 1, 1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME, START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('CCMS', sysdate, sysdate, 1, 1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('CCR', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('CWA', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('CIS', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('Eforms', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('MAAT', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('MAAT/LIBRA', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('Management Information', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('OBIEE', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('PIMS', sysdate, sysdate, 1,  1, sysdate);
	
INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('LAA Online Portal', sysdate, sysdate, 1,  1, sysdate);

INSERT INTO GI_IT_SYSTEMS	
	(SYS_NAME,START_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
	VALUES
	('Tender Verification', sysdate, sysdate, 1,  1, sysdate);


COMMIT;
end;	
