--- GI_OFFICE

begin


INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Birmingham', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Brighton', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Bristol', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Cambridge', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Cardiff', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Cheltenham PDS', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Darlington PDS', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Leeds', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Liverpool', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Manchester', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Nottingham', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Petty France', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Pontypridd PDS', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Reading', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('South Tyneside', SYSDATE, 1, SYSDATE, SYSDATE, 1);
INSERT INTO GI_OFFICE (OFFICE_NAME, START_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY) VALUES('Swansea PDS', SYSDATE, 1, SYSDATE, SYSDATE, 1);

COMMIT; 
end;
