--- GI_LOOKUP_TYPES


Begin	
	

INSERT INTO GI_LOOKUP_TYPES	
	(LOOKUP_TYPE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
VALUES
	('Benefits', sysdate, 1, 1, sysdate);
	
INSERT INTO GI_LOOKUP_TYPES	
	(LOOKUP_TYPE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
VALUES
	('Initiator Involvement', sysdate, 1, 1, sysdate);
	
INSERT INTO GI_LOOKUP_TYPES	
	(LOOKUP_TYPE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
VALUES
	('Affected Area', sysdate, 1, 1, sysdate);
	
INSERT INTO GI_LOOKUP_TYPES	
	(LOOKUP_TYPE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
VALUES
	('Current Status', sysdate, 1, 1, sysdate);
	
INSERT INTO GI_LOOKUP_TYPES	
	(LOOKUP_TYPE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
VALUES
	('Category', sysdate, 1, 1, sysdate);

INSERT INTO GI_LOOKUP_TYPES 
      (LOOKUP_TYPE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
VALUES
      ('Participation Level', sysdate, 1, 1, sysdate);

INSERT INTO GI_LOOKUP_TYPES 
      (LOOKUP_TYPE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
VALUES
      ('Affected Systems', sysdate, 1, 1, sysdate);


COMMIT;
end;	
